
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("car_model/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("car_model", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit car_model</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="FK_CAR_MAKE">Fabricante</label>
        </td>
        <td align="left">
            <select name="FK_CAR_MAKE" id="FK_CAR_MAKE" class="form-control">
                <option>Selecciona un fabricante</option>
                <?php 
                foreach ($car_makes as $make) {
                    echo "<option ".(($this->view->FK_CAR_MAKE == $make->ID_CAR_MAKE)?'selected':'')." value='" . $make->ID_CAR_MAKE . "'>$make->name</option>";
                }
                ?>
            </select>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("ID_CAR_MODEL") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
