<?php echo $this->getContent() ?>

<div class="row">
    <div align="right">
        <?= $this->tag->linkTo(["car_model/new", "Crear un nuevo modelo", 'class' => 'btn btn-primary']);?>
    </div>
</div>

<div class="row">
<?php
if ($car_models->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Fabricante</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($car_models as $car_model) {
            echo '<tr>';
                echo '<td>'.$car_model->getIdCarModel().'</td>';
                echo '<td>'.$car_model->getName().'</td>';
                echo '<td>'.$car_model->car_make->name.'</td>';
                echo '<td>'.(($car_model->getStatus() == 1)?'Activo':'Inactivo').'</td>';
                echo '<td>'.$this->tag->linkTo(['car_model/edit/'.$car_model->getIdCarModel(), 'Editar', 'class' => 'btn btn-secondary']).
                            (($car_model->getStatus() == 1)?$this->tag->linkTo(['car_model/delete/'.$car_model->getIdCarModel(), 'Eliminar', 'class' => 'btn btn-danger']):'').'</td>';
            echo '</tr>';
        }
        ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Car Models quantity: <?php echo $car_models->count(); ?></td>
            </tr>
        </tfoot>
    </table>
<?php
}
?>
</div>
