
<?php echo $this->tag->form("car_model/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("car_model", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create car_model</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date_create">Date Of Create</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date_create", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date_update">Date Of Update</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date_update", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="FK_CAR_MAKE">FK Of CAR Of MAKE</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("FK_CAR_MAKE", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
