<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("car_model/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("car_model/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>ID Of CAR Of MODEL</th>
            <th>Name</th>
            <th>Status</th>
            <th>Date Of Create</th>
            <th>Date Of Update</th>
            <th>FK Of CAR Of MAKE</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $car_model) { ?>
        <tr>
            <td><?php echo $car_model->ID_CAR_MODEL ?></td>
            <td><?php echo $car_model->name ?></td>
            <td><?php echo $car_model->status ?></td>
            <td><?php echo $car_model->date_create ?></td>
            <td><?php echo $car_model->date_update ?></td>
            <td><?php echo $car_model->FK_CAR_MAKE ?></td>
            <td><?php echo $this->tag->linkTo(array("car_model/edit/" . $car_model->ID_CAR_MODEL, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("car_model/delete/" . $car_model->ID_CAR_MODEL, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("car_model/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("car_model/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("car_model/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("car_model/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
