
<?php echo $this->tag->form("car_generation/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("car_generation", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create car_generation</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="year_begin">Year Of Begin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("year_begin", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="year_end">Year Of End</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("year_end", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date_create">Date Of Create</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date_create", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date_update">Date Of Update</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date_update", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="FK_CAR_MODEL">FK Of CAR Of MODEL</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("FK_CAR_MODEL", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
